<a href="https://colab.research.google.com/github/L1ght6/MN_HORA_4_9/blob/main/%D0%9B%D0%A01_%D0%93%D0%BE%D1%80%D0%B0%D0%A4%D0%86%D0%A24_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


Гора Р.В

---
ФІТ 4-9


https://colab.research.google.com/drive/1DBX9jYgxlcYkA3V1ytqH6CD18AtOuYpm?usp=sharing

## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np

print("Версія NumPy:", np.__version__)

Версія NumPy: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr_1 = np.array([2, 4, 6, 8, 10])
print("Масив:", arr_1)
print("Тип об'єкта:", type(arr_1))

Масив: [ 2  4  6  8 10]
Тип об'єкта: <class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [4]:
zeros_arr = np.zeros(10)
print("Масив із 10 нулів:", zeros_arr)

ones_arr = np.ones(8)
print("Масив із 8 одиниць:", ones_arr)

sevens_arr = np.full(6, 7)
print("Масив із 6 сімок:", sevens_arr)

Масив із 10 нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Масив із 8 одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
Масив із 6 сімок: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [5]:
arr_1_to_20 = np.arange(1, 21)
print("Від 1 до 20 включно:", arr_1_to_20)

even_arr = np.arange(2, 21, 2)
print("Парні числа від 2 до 20:", even_arr)

Від 1 до 20 включно: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні числа від 2 до 20: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [6]:
linspace_arr = np.linspace(0, 1, 11)
print("11 рівновіддалених чисел від 0 до 1:", linspace_arr)

11 рівновіддалених чисел від 0 до 1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [7]:
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("Матриця 3x4:\n", matrix_3x4)

Матриця 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [8]:
print("Кількість вимірів (ndim):", matrix_3x4.ndim)
print("Форма (shape):", matrix_3x4.shape)
print("Загальна кількість елементів (size):", matrix_3x4.size)
print("Тип даних елементів (dtype):", matrix_3x4.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних елементів (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [9]:
float_arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = float_arr.astype(int)
print("Початковий масив:", float_arr)
print("Масив цілих чисел:", int_arr)

Початковий масив: [1.2 3.5 5.7 7.9]
Масив цілих чисел: [1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [10]:
arr_8 = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Перший елемент:", arr_8[0])
print("Останній елемент:", arr_8[-1])
print("Елементи з індексами від 2 до 5 включно:", arr_8[2:6])
print("Кожен другий елемент:", arr_8[::2])

Перший елемент: 10
Останній елемент: 80
Елементи з індексами від 2 до 5 включно: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [11]:
matrix_9 = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
])

print("Елемент 7:", matrix_9[1, 2])
print("Другий рядок:", matrix_9[1, :])
print("Третій стовпець:", matrix_9[:, 2])
print("Підматриця (останні два рядки, перші два стовпці):\n", matrix_9[-2:, :2])

Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця (останні два рядки, перші два стовпці):
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [12]:
arr_10 = np.arange(1, 16)
arr_10[5:10] = 0
print("Масив після заміни елементів на 0:", arr_10)

Масив після заміни елементів на 0: [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [13]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)

Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [14]:
arr_12 = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr_12))
print("Середнє значення:", np.mean(arr_12))
print("Мінімум:", np.min(arr_12))
print("Максимум:", np.max(arr_12))
print("Медіана:", np.median(arr_12))
print("Стандартне відхилення:", np.std(arr_12))

Сума: 108
Середнє значення: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [15]:
matrix_13 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Сума всіх елементів:", np.sum(matrix_13))
print("Сума по кожному стовпцю:", np.sum(matrix_13, axis=0))
print("Сума по кожному рядку:", np.sum(matrix_13, axis=1))
print("Середнє значення по кожному стовпцю:", np.mean(matrix_13, axis=0))

Сума всіх елементів: 45
Сума по кожному стовпцю: [12 15 18]
Сума по кожному рядку: [ 6 15 24]
Середнє значення по кожному стовпцю: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [16]:
arr_14 = np.arange(1, 11)

print("Квадрат кожного елемента:", np.square(arr_14))
print("Квадратний корінь кожного елемента:", np.sqrt(arr_14))
print("Натуральний логарифм кожного елемента:", np.log(arr_14))

Квадрат кожного елемента: [  1   4   9  16  25  36  49  64  81 100]
Квадратний корінь кожного елемента: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральний логарифм кожного елемента: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [17]:
arr_15 = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Більші за 15:", arr_15[arr_15 > 15])
print("Парні числа:", arr_15[arr_15 % 2 == 0])
print("У діапазоні від 10 до 30 включно:", arr_15[(arr_15 >= 10) & (arr_15 <= 30)])

Більші за 15: [18 21 25 30 34]
Парні числа: [12 18 30 34]
У діапазоні від 10 до 30 включно: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [18]:
arr_16 = np.array([-5, 3, -2, 8, -1, 10, 0])
arr_16[arr_16 < 0] = 0
print("Масив без від'ємних значень:", arr_16)

Масив без від'ємних значень: [ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [19]:
np.random.seed(42)
arr_17 = np.random.randint(0, 101, 20)

print("Згенерований масив:", arr_17)
print("Більші за 50:", np.sum(arr_17 > 50))
print("Менші або дорівнюють 50:", np.sum(arr_17 <= 50))

Згенерований масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Більші за 50: 12
Менші або дорівнюють 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [20]:
arr_18 = np.arange(1, 25)

mat_4x6 = arr_18.reshape(4, 6)
print("Форма матриці 4x6:", mat_4x6.shape)

mat_6x4 = arr_18.reshape(6, 4)
print("Форма матриці 6x4:", mat_6x4.shape)

arr_3d = arr_18.reshape(2, 3, 4)
print("Форма 3D-масиву:", arr_3d.shape)

Форма матриці 4x6: (4, 6)
Форма матриці 6x4: (6, 4)
Форма 3D-масиву: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [21]:
A_19 = np.array([[1, 2], [3, 4]])
B_19 = np.array([[5, 6], [7, 8]])

print("Вертикальне об'єднання (vstack):\n", np.vstack((A_19, B_19)))
print("Горизонтальне об'єднання (hstack):\n", np.hstack((A_19, B_19)))

Вертикальне об'єднання (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтальне об'єднання (hstack):
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [22]:
matrix_20 = np.arange(1, 13).reshape(3, 4)

flat_arr = matrix_20.flatten()
ravel_arr = matrix_20.ravel()

print("Flatten:", flat_arr)
print("Ravel:", ravel_arr)

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [23]:
a_21 = np.array([2, 4, 6])
b_21 = np.array([1, 3, 5])

print("Сума векторів:", a_21 + b_21)
print("Різниця векторів:", a_21 - b_21)
print("Вектор a * 3:", a_21 * 3)
print("Вектор b * 3:", b_21 * 3)

Сума векторів: [ 3  7 11]
Різниця векторів: [1 1 1]
Вектор a * 3: [ 6 12 18]
Вектор b * 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [24]:
a_22 = np.array([1, 2, 3])
b_22 = np.array([4, 5, 6])

print("Скалярний добуток (np.dot):", np.dot(a_22, b_22))
print("Скалярний добуток (оператор @):", a_22 @ b_22)

Скалярний добуток (np.dot): 32
Скалярний добуток (оператор @): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [25]:
v_23 = np.array([3, 4])
norm_v = np.linalg.norm(v_23)
v_normalized = v_23 / norm_v

print("Евклідова норма:", norm_v)
print("Нормалізований вектор:", v_normalized)
print("Перевірка норми (має бути 1.0):", np.linalg.norm(v_normalized))

Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]
Перевірка норми (має бути 1.0): 1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [26]:
a_24 = np.array([1, 0, 0])
b_24 = np.array([0, 1, 0])

cross_prod = np.cross(a_24, b_24)
print("Векторний добуток:", cross_prod)

Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [27]:
a_25 = np.array([1, 2])
b_25 = np.array([2, 1])

dot_product = np.dot(a_25, b_25)
norm_a = np.linalg.norm(a_25)
norm_b = np.linalg.norm(b_25)

cos_angle = dot_product / (norm_a * norm_b)
angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)

print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle_deg)

Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [28]:
A_26 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Транспонована через .T:\n", A_26.T)
print("Транспонована через np.transpose:\n", np.transpose(A_26))

Транспонована через .T:
 [[1 4]
 [2 5]
 [3 6]]
Транспонована через np.transpose:
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [29]:
A_27 = np.array([[1, 2], [3, 4]])
B_27 = np.array([[2, 0], [1, 2]])

print("Поелементний добуток A * B:\n", A_27 * B_27)
print("Матричний добуток A @ B:\n", A_27 @ B_27)

Поелементний добуток A * B:
 [[2 0]
 [3 8]]
Матричний добуток A @ B:
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [30]:
A_28 = np.array([
    [4, 7],
    [2, 6]
])

det_A = np.linalg.det(A_28)
inv_A = np.linalg.inv(A_28)

print("Визначник:", det_A)
print("Обернена матриця:\n", inv_A)
print("Перевірка (A @ inv_A):\n", np.round(A_28 @ inv_A))

Визначник: 10.000000000000002
Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка (A @ inv_A):
 [[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [31]:
A_29 = np.array([
    [2, 1],
    [1, 3]
])
b_29 = np.array([5, 6])

solution = np.linalg.solve(A_29, b_29)
print("Розв'язок системи [x, y]:", solution)

Розв'язок системи [x, y]: [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [32]:
identity_matrix = np.eye(4)
random_matrix = np.random.randint(1, 10, (4, 4))

result = random_matrix @ identity_matrix

print("Одинична матриця:\n", identity_matrix)
print("Довільна матриця:\n", random_matrix)
print("Матриці ідентичні після множення:", np.allclose(random_matrix, result))

Одинична матриця:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Довільна матриця:
 [[2 5 1 6]
 [9 1 3 7]
 [4 9 3 5]
 [3 7 5 9]]
Матриці ідентичні після множення: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [33]:
A_31 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Матриця після додавання 10:\n", A_31 + 10)

Матриця після додавання 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [34]:
A_32 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
v_32 = np.array([10, 20, 30])

result_32 = A_32 + v_32
print("Матриця + вектор:\n", result_32)
# Аналіз: Вектор v має розмірність (3,). Матриця A має розмірність (3, 3).
# NumPy автоматично "розтягує" (broadcast) вектор v вздовж кожного рядка матриці A і поелементно додає його значення.

Матриця + вектор:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [35]:
A_33 = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

means = A_33.mean(axis=0)
stds = A_33.std(axis=0)
normalized_A = (A_33 - means) / stds

print("Нормалізована матриця (по стовпцях):\n", normalized_A)

Нормалізована матриця (по стовпцях):
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [36]:
np.random.seed(42)

rand_ints = np.random.randint(1, 101, 10)
print("10 випадкових цілих чисел:", rand_ints)

rand_floats = np.random.rand(3, 3)
print("Матриця 3x3 [0, 1):\n", rand_floats)

normal_dist = np.random.randn(1000)
print("Середнє нормального розподілу:", np.mean(normal_dist))
print("Стандартне відхилення:", np.std(normal_dist))

10 випадкових цілих чисел: [52 93 15 72 61 21 83 87 75 75]
Матриця 3x3 [0, 1):
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє нормального розподілу: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [37]:
np.random.seed(42)
grades = np.random.randint(0, 101, 30)

print("Оцінки:", grades)
print("Середня оцінка:", np.mean(grades))
print("Медіана:", np.median(grades))
print("Найвища оцінка:", np.max(grades))
print("Найнижча оцінка:", np.min(grades))
print("Студентів >= 60:", np.sum(grades >= 60))
print("Відсоток студентів >= 90:", np.mean(grades >= 90) * 100, "%")

Оцінки: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища оцінка: 99
Найнижча оцінка: 1
Студентів >= 60: 13
Відсоток студентів >= 90: 6.666666666666667 %


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [38]:
sales = np.array([
    [120, 150, 170, 160],
    [80,  90,  100, 110],
    [200, 180, 210, 230]
])

print("Загальні продажі кожного товару:", sales.sum(axis=1))
print("Загальні продажі у кожному місяці:", sales.sum(axis=0))
print("Товар із найбільшими продажами (індекс):", np.argmax(sales.sum(axis=1)))
print("Місяць із найбільшими продажами (індекс):", np.argmax(sales.sum(axis=0)))
print("Середній обсяг продажів кожного товару:", sales.mean(axis=1))

Загальні продажі кожного товару: [600 380 820]
Загальні продажі у кожному місяці: [400 420 480 500]
Товар із найбільшими продажами (індекс): 2
Місяць із найбільшими продажами (індекс): 3
Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [39]:
np.random.seed(42)
M_37 = np.random.randint(1, 21, (5, 5))
print("Початкова матриця:\n", M_37)

print("Сума головної діагоналі:", np.trace(M_37))

print("Сума побічної діагоналі:", np.sum(np.diag(np.fliplr(M_37))))

print("Максимальний елемент кожного рядка:", M_37.max(axis=1))
print("Мінімальний елемент кожного стовпця:", M_37.min(axis=0))

mean_val = M_37.mean()
M_37[M_37 < mean_val] = 0
print(f"Матриця після заміни елементів < {mean_val:.2f} на 0:\n", M_37)

Початкова матриця:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]
Сума головної діагоналі: 59
Сума побічної діагоналі: 32
Максимальний елемент кожного рядка: [20 19 12 17 19]
Мінімальний елемент кожного стовпця: [ 2  1  2 11  4]
Матриця після заміни елементів < 10.52 на 0:
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [40]:
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9]
])

dist_1_2 = np.linalg.norm(X[0] - X[1])
dist_1_3 = np.linalg.norm(X[0] - X[2])
dist_2_3 = np.linalg.norm(X[1] - X[2])

print("Відстань між 1-м і 2-м рядками:", dist_1_2)
print("Відстань між 1-м і 3-м рядками:", dist_1_3)
print("Відстань між 2-м і 3-м рядками:", dist_2_3)

Відстань між 1-м і 2-м рядками: 1.7320508075688772
Відстань між 1-м і 3-м рядками: 5.196152422706632
Відстань між 2-м і 3-м рядками: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [41]:
M_39 = np.random.randint(1, 10, (4, 4))
print("Оригінальна матриця:\n", M_39)

row_norms = np.linalg.norm(M_39, axis=1, keepdims=True)
normalized_M_39 = M_39 / row_norms

print("Нормалізована матриця (по рядках):\n", normalized_M_39)
print("Норми нових рядків:", np.linalg.norm(normalized_M_39, axis=1))

Оригінальна матриця:
 [[7 4 9 3]
 [5 3 7 5]
 [9 7 2 4]
 [9 2 9 5]]
Нормалізована матриця (по рядках):
 [[0.56225353 0.32128773 0.7228974  0.2409658 ]
 [0.48112522 0.28867513 0.67357531 0.48112522]
 [0.73484692 0.57154761 0.16329932 0.32659863]
 [0.65121714 0.14471492 0.65121714 0.3617873 ]]
Норми нових рядків: [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [42]:
A_40 = np.array([
    [1,  2,  1],
    [2,  1, -1],
    [3, -1,  2]
])
b_40 = np.array([9, 8, 3])

x_40 = np.linalg.solve(A_40, b_40)
print("Вектор розв'язку x:", x_40)

check = A_40 @ x_40
print("Перевірка A @ x:", check)
print("Вектор b:", b_40)
print("Результати збігаються:", np.allclose(check, b_40))

Вектор розв'язку x: [ 2.22222222  3.44444444 -0.11111111]
Перевірка A @ x: [9. 8. 3.]
Вектор b: [9 8 3]
Результати збігаються: True


**Висновок:**
У ході лабораторної роботи успішно опановано базовий інструментарій NumPy. На практиці закріплено навички створення, індексації та зміни форми багатовимірних масивів. Опановано векторизовані обчислення та механізм broadcasting (замість повільних циклів), генерацію випадкових даних, а також використання модуля `np.linalg` для виконання матричних операцій і розв'язання систем лінійних рівнянь.